on: workflow_dispatch 
    
jobs:
  # This workflow contains a single job called "traffic"
  traffic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: "main"
    
    # Calculates traffic and clones and stores in CSV file
    - name: Retrieve new traffic 
      uses: sangonzal/repository-traffic-action@v.0.1.6
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }} 
     
     # Uploades the new views to Google Drive
    - name: Upload to Google Drive
      uses: Jodebu/upload-to-drive@master
      with:
        target: traffic
        credentials: ${{ secrets.DRIVE_GSA_CREDENTIALS }}
        folder: $ {{ secrets.DRIVE_FOLDER_ID }}
